### PR TITLE
port to willie 5.0.0 by fixing logging

### PR DESCRIPTION
**Pull request by anarcat**
it seems that is all that is needed. i note, however, it would be
useful to have a cleaner generator to avoid having to do the dumb:

```
log = logger.get_logger(__name__)
```

i did in this module in _every_ module out there...

not sure how that could work however.

### CODE REVIEW

**Comment by anarcat** [comment]
there seems to be a few ideas [in this stackoverflow discussion](https://stackoverflow.com/questions/1095543/get-name-of-calling-functions-module-in-python) including using the `inspect` module or the `sys._current_frames()` functions.

maybe it would be as simple as:

    import inspect
    # [...]
    def getlogger(mod = None):
      if mod is None:
        frm = inspect.stack()[1]
        mod = inspect.getmodule(frm[0]).__name__
      # [...]

**Comment by dgw** [comment]
@anarcat Is this change still needed in Sopel 6? If so, feel free to rebase & resolve merge conflicts.

**Comment by anarcat** [comment]
> @anarcat Is this change still needed in Sopel 6? If so, feel free to rebase & resolve merge conflicts.

i don't know, really. i don't use bookie anymore, the author completely abandoned the project and no one else picked it up, and my friend running the service since then switched to wallabag, so i don't really use this plugin anymore.

i would assume the changes are still needed, but maybe it would be best to just simply remove the plugin as no one probably uses it anymore...

**Comment by dgw** [comment]
Huh, you're right. Bookie.io won't even load any more, the last commits to Bookie on GitHub were made three years ago, and even the apparent new site for Bookie (bmarks.us) won't load either.

I'll dig a bit more, but the ultimate outcome looks like it'll be removing this outdated module. Thanks.

**Pull request closed without merging**
