### PR TITLE
make sure we call the right function to sanitize IDNs

### PR DESCRIPTION
**Pull request by anarcat**
in the bookie plugin, some code was too quickly copy-pasted and never tested

this probably never worked, but should work now

### CODE REVIEW

**Comment by anarcat** [comment]
bump. this is a trivial fix that should be merged. anything else i should do here?

**Comment by dgw** [comment]
The `bookie` module was removed, as the service it relied upon appeared to be dead.

**Comment by anarcat** [comment]
:sadtrombone:

thanks for cleaning uo!

**Comment by dgw** [comment]
Yeah, lots of dead stuff around here (in my fork too), haha. Cleanup is good!

**Pull request closed without merging**
